name: Build and Package Flutter APK

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.5'  # 设置你想要使用的 Flutter 版本

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: flutter-apk
        path: android/app-release.apk  # 修改为你的 APK 路径
